// Köppen-Geiger classes + official colors, from Beck et al. (2023) legend.txt.
// Class ID is the integer pixel value in koppen_geiger_*.tif.
export const KOPPEN_CLASSES = {
  1:  { symbol: 'Af',  name: 'Tropical, rainforest',                  color: 'rgb(0, 0, 255)' },
  2:  { symbol: 'Am',  name: 'Tropical, monsoon',                     color: 'rgb(0, 120, 255)' },
  3:  { symbol: 'Aw',  name: 'Tropical, savannah',                    color: 'rgb(70, 170, 250)' },
  4:  { symbol: 'BWh', name: 'Arid, desert, hot',                     color: 'rgb(255, 0, 0)' },
  5:  { symbol: 'BWk', name: 'Arid, desert, cold',                    color: 'rgb(255, 150, 150)' },
  6:  { symbol: 'BSh', name: 'Arid, steppe, hot',                     color: 'rgb(245, 165, 0)' },
  7:  { symbol: 'BSk', name: 'Arid, steppe, cold',                    color: 'rgb(255, 220, 100)' },
  8:  { symbol: 'Csa', name: 'Temperate, dry summer, hot summer',     color: 'rgb(255, 255, 0)' },
  9:  { symbol: 'Csb', name: 'Temperate, dry summer, warm summer',    color: 'rgb(200, 200, 0)' },
  10: { symbol: 'Csc', name: 'Temperate, dry summer, cold summer',    color: 'rgb(150, 150, 0)' },
  11: { symbol: 'Cwa', name: 'Temperate, dry winter, hot summer',     color: 'rgb(150, 255, 150)' },
  12: { symbol: 'Cwb', name: 'Temperate, dry winter, warm summer',    color: 'rgb(100, 200, 100)' },
  13: { symbol: 'Cwc', name: 'Temperate, dry winter, cold summer',    color: 'rgb(50, 150, 50)' },
  14: { symbol: 'Cfa', name: 'Temperate, no dry season, hot summer',  color: 'rgb(200, 255, 80)' },
  15: { symbol: 'Cfb', name: 'Temperate, no dry season, warm summer', color: 'rgb(100, 255, 80)' },
  16: { symbol: 'Cfc', name: 'Temperate, no dry season, cold summer', color: 'rgb(50, 200, 0)' },
  17: { symbol: 'Dsa', name: 'Cold, dry summer, hot summer',          color: 'rgb(255, 0, 255)' },
  18: { symbol: 'Dsb', name: 'Cold, dry summer, warm summer',         color: 'rgb(200, 0, 200)' },
  19: { symbol: 'Dsc', name: 'Cold, dry summer, cold summer',         color: 'rgb(150, 50, 150)' },
  20: { symbol: 'Dsd', name: 'Cold, dry summer, very cold winter',    color: 'rgb(150, 100, 150)' },
  21: { symbol: 'Dwa', name: 'Cold, dry winter, hot summer',          color: 'rgb(170, 175, 255)' },
  22: { symbol: 'Dwb', name: 'Cold, dry winter, warm summer',         color: 'rgb(90, 120, 220)' },
  23: { symbol: 'Dwc', name: 'Cold, dry winter, cold summer',         color: 'rgb(75, 80, 180)' },
  24: { symbol: 'Dwd', name: 'Cold, dry winter, very cold winter',    color: 'rgb(50, 0, 135)' },
  25: { symbol: 'Dfa', name: 'Cold, no dry season, hot summer',       color: 'rgb(0, 255, 255)' },
  26: { symbol: 'Dfb', name: 'Cold, no dry season, warm summer',      color: 'rgb(55, 200, 255)' },
  27: { symbol: 'Dfc', name: 'Cold, no dry season, cold summer',      color: 'rgb(0, 125, 125)' },
  28: { symbol: 'Dfd', name: 'Cold, no dry season, very cold winter', color: 'rgb(0, 70, 95)' },
  29: { symbol: 'ET',  name: 'Polar, tundra',                         color: 'rgb(178, 178, 178)' },
  30: { symbol: 'EF',  name: 'Polar, frost',                          color: 'rgb(102, 102, 102)' },
};
